In [181]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [183]:
a=[]  # Will store doctor names
h=[]  #  Will store clinic addresses

# Define a function to extract doctor names and clinic addresses from a webpage
def fun(webpage):
    soup=BeautifulSoup(webpage,'lxml')  # Create a BeautifulSoup object to parse the HTML

    b=soup.find_all('a',class_='doctor-card__name')  # Find all 'a' tags with the class 'doctor-card__name'

    # Iterate through the found 'a' tags and extract the text content (doctor names)
    for i in b:
      a.append(i.text.strip())  # Append the cleaned name to the 'a' list

    # Find all 'div' tags with the class 'doctor-card__clinic'
    k=soup.find_all('div',class_='doctor-card__clinic')
    
    # Iterate through the found 'div' tags and extract the text content (clinic addresses)
    for i in k:
      h.append(i.text.strip())   # Append the cleaned address to the 'h' list
        
    # Return both lists containing extracted data
    return a,h


# Loop through multiple pages of the website
for i in range(1,15):
    # Construct the URL for each page

    webpage=requests.get(f'https://us-uk.bookimed.com/doctors/country=germany/page={i}/',).text  # Fetch HTML content of the page
    y=fun(webpage)  # Call the 'fun' function to extract data from the page

In [185]:
y  # Output the extracted data (doctor names and clinic addresses)

(['Ralf Buhl',
  'Ralf Buhl',
  'Andreas Gross',
  'Andreas Gross',
  'Peter Paul Urban',
  'Peter Paul Urban',
  'Paul Kremer',
  'Paul Kremer',
  'Ulrich Schaudig',
  'Ulrich Schaudig',
  'Boris Pfaffenbach',
  'Boris Pfaffenbach',
  'Elke Jaeger',
  'Elke Jaeger',
  'Sasсha Flohé',
  'Sasсha Flohé',
  'Karl J. Oldhafer',
  'Karl J. Oldhafer',
  'Plamen Staikov',
  'Plamen Staikov',
  'Andreas Sesterhenn',
  'Andreas Sesterhenn',
  'Siegbert Rossol',
  'Siegbert Rossol',
  'Ahmet Elmaagacli',
  'Ahmet Elmaagacli',
  'Gerhard Gebauer',
  'Gerhard Gebauer',
  'Eckhart Weidmann',
  'Eckhart Weidmann',
  'Manuela Seifert',
  'Manuela Seifert',
  'Marcus Goyzer',
  'Marcus Goyzer',
  'Jens E. Meyer',
  'Jens E. Meyer',
  'Uta Meyding-Lamade',
  'Uta Meyding-Lamade',
  'Jörg B. Engel',
  'Jörg B. Engel',
  'Axel Stang',
  'Axel Stang',
  'Stefanie Veit',
  'Stefanie Veit',
  'Jörg B. Engel',
  'Jörg B. Engel',
  'Uta Meyding-Lamade',
  'Uta Meyding-Lamade',
  'Uwe Kehler',
  'Uwe Kehler',
  'Ulrich Schaller',
  'Ulrich Schaller',
  'Christoph Rangger',
  'Christoph Rangger',
  'Thomas W Kraus',
  'Thomas W Kraus',
  'Peter Ulrich',
  'Peter Ulrich',
  'Michael Van Kampen',
  'Michael Van Kampen',
  'Philipp-Andreas Hessler',
  'Philipp-Andreas Hessler',
  'Ulrich-Frank Pape',
  'Ulrich-Frank Pape',
  'Christian Sander',
  'Christian Sander',
  'Prof Dr Hendrik Wolff',
  'Prof Dr Hendrik Wolff',
  'Jorn Halberstadt',
  'Jorn Halberstadt',
  'Matthias Schlensak',
  'Matthias Schlensak',
  'Stephan Willems',
  'Stephan Willems',
  'Bodo Lippitz',
  'Bodo Lippitz',
  'Antje-Katrin Hofele',
  'Antje-Katrin Hofele',
  'Sven Rogmans',
  'Sven Rogmans',
  'Peter Schenker',
  'Peter Schenker',
  'Marcel Dihne',
  'Marcel Dihne',
  'Phd Viola Fox',
  'Phd Viola Fox',
  'Kristyan Vaik',
  'Kristyan Vaik',
  'Christian Wülfing',
  'Christian Wülfing',
  'Michael Hoffmann',
  'Michael Hoffmann',
  'Sven Propson',
  'Sven Propson',
  'Jurgen Stein',
  'Jurgen Stein',
  'Holger Bahn',
  'Holger Bahn',
  'Konrad Stubbig',
  'Konrad Stubbig',
  'Arun Kumarasamy',
  'Arun Kumarasamy',
  'Claudius Teupe',
  'Claudius Teupe',
  'Ralf Jung',
  'Ralf Jung',
  'Anke Reitter',
  'Anke Reitter',
  'Ralf Kolvenbach',
  'Ralf Kolvenbach',
  'Wolfgang Nebelung',
  'Wolfgang Nebelung',
  'Rolf Michael Klein',
  'Rolf Michael Klein',
  'Wolfgang Steinke',
  'Wolfgang Steinke',
  'Yorg Herdmann',
  'Yorg Herdmann',
  'Aristoteles Giagonidis',
  'Aristoteles Giagonidis',
  'Michael Schmoeckel',
  'Michael Schmoeckel',
  'Gerd Manthei',
  'Gerd Manthei',
  'Silke Tribius',
  'Silke Tribius',
  'Holger Maul',
  'Holger Maul',
  'Bernd Schroeder',
  'Bernd Schroeder',
  'Hita Tushar Dave',
  'Hita Tushar Dave',
  'Guenter Seidel',
  'Guenter Seidel',
  'Thomas Grundmann',
  'Thomas Grundmann',
  'Detlef Rose',
  'Detlef Rose',
  'Juergen Pohl',
  'Juergen Pohl',
  'Sebastian Keil',
  'Sebastian Keil',
  'Martin Peters',
  'Martin Peters',
  'Petra Reemts',
  'Petra Reemts',
  'Norbert Schmitz',
  'Norbert Schmitz',
  'Klaus D. Diemel',
  'Klaus D. Diemel',
  'Axel Hillmann',
  'Axel Hillmann',
  'Agoritsa Stergiou-Tsaroucha',
  'Agoritsa Stergiou-Tsaroucha',
  'Veit Becker',
  'Veit Becker',
  'Juergen Faiss',
  'Juergen Faiss',
  'Stefan Schreiber',
  'Stefan Schreiber',
  'Thomas Mansfeld',
  'Thomas Mansfeld',
  'Johann Pichl',
  'Johann Pichl',
  'Thomas Carus',
  'Thomas Carus',
  'Thomas Verse',
  'Thomas Verse',
  'Henrik Becker',
  'Henrik Becker',
  'Milan Lisy',
  'Milan Lisy',
  'Markus Düx',
  'Markus Düx',
  'Matthias W. Lorenz',
  'Matthias W. Lorenz',
  'Gerhart Tseslinsky',
  'Gerhart Tseslinsky',
  'Max Zegelman',
  'Max Zegelman',
  'Eduard Becht',
  'Eduard Becht',
  'Gunther Wiest',
  'Gunther Wiest',
  'Jorg Handschel',
  'Jorg Handschel',
  'Garald Krentel',
  'Garald Krentel',
  'Jan Fichtner',
  'Jan Fichtner',
  'Gerd Degoutrie',
  'Gerd Degoutrie',
  'Jürgen Kiwit',
  'Jürgen Kiwit',
  'Jorn Jorgensen',
  'Jorn Jorgensen',
  'Clayton Kraft',
  'Clayton Kraft',
  'Michael Unch',
  'Michael Unch',
  'Bertram Glaß',
  'Bertram Glaß',
  'Professor Volker Budach',
  'Professor Volker Budach',
  'Doctor Maria Steingraber',
  'Doctor Maria Steingraber',
  'Professor Simone Marnitz',
  'Professor Simone Marnitz',
  'Sebastian Melchior',
  'Sebastian Melchior',
  'Mark Schrader',
  'Mark Schrader',
  'Jaroslav Benedik',
  'Jaroslav Benedik',
  'Carsten Michael Oberhoff',
  'Carsten Michael Oberhoff',
  'Stefan Dresel',
  'Stefan Dresel',
  'Robert Krempien',
  'Robert Krempien',
  'Jorg Groticke',
  'Jorg Groticke',
  'Ludger Wilhelm Poll',
  'Ludger Wilhelm Poll',
  'Martin Friedrich',
  'Martin Friedrich',
  'Martin Marianowicz',
  'Martin Marianowicz',
  'Michael Stoffel',
  'Michael Stoffel',
  'Markus Heuser',
  'Markus Heuser',
  'Yu-mi Ryang',
  'Yu-mi Ryang',
  'Huseyin Bektas',
  'Huseyin Bektas',
  'Bernd Hertenstein',
  'Bernd Hertenstein',
  'Markus Zutt',
  'Markus Zutt',
  'Arne-Joern Lemke',
  'Arne-Joern Lemke',
  'Erik Chankiewitz',
  'Erik Chankiewitz',
  'Andreas Schuler',
  'Andreas Schuler',
  'Andreas Kastrup',
  'Andreas Kastrup',
  'Klaus Luque',
  'Klaus Luque',
  'Mustafa Aydogdu',
  'Mustafa Aydogdu',
  'Johann Ockenga',
  'Johann Ockenga',
  'Jan Korde',
  'Jan Korde',
  'Krystyna Wisniewski',
  'Krystyna Wisniewski',
  'Michael Paul Hahn',
  'Michael Paul Hahn',
  'Andreas Naumann',
  'Andreas Naumann',
  'Uwe Neubauer',
  'Uwe Neubauer',
  'Jоrn H. Witt',
  'Jоrn H. Witt',
  'Marco Dorshner',
  'Marco Dorshner',
  'Guido Gerken',
  'Guido Gerken',
  'Martin Stuschke',
  'Martin Stuschke',
  'Andreas Hufnagel',
  'Andreas Hufnagel',
  'Dietrich W. Beelen',
  'Dietrich W. Beelen',
  'Daniela Dorshner-Gerlofs',
  'Daniela Dorshner-Gerlofs',
  'Ruud Gerlofs',
  'Ruud Gerlofs',
  'Human Zafiarian',
  'Human Zafiarian',
  'Roland Veltkamp',
  'Roland Veltkamp',
  'Kristian Reich',
  'Kristian Reich',
  'Volker Steinkraus',
  'Volker Steinkraus',
  'L. Rainer Rupprecht',
  'L. Rainer Rupprecht',
  'Eckhart Kämpgen',
  'Eckhart Kämpgen',
  'Uwe Trefzer',
  'Uwe Trefzer',
  'Christoph Kleinschnitz',
  'Christoph Kleinschnitz',
  'Ulrich Schäfer',
  'Ulrich Schäfer',
  'Frank Hartmann',
  'Frank Hartmann',
  'Cyrus Klostermann',
  'Cyrus Klostermann',
  'Stephan Gielen',
  'Stephan Gielen',
  'Wolfgang Hiller',
  'Wolfgang Hiller',
  'Dr. Marion Eckert',
  'Dr. Marion Eckert',
  'Prof. Uwe Mellies',
  'Prof. Uwe Mellies',
  'Prof. Heiko Stern',
  'Prof. Heiko Stern',
  'Dr. Simon Mayer',
  'Dr. Simon Mayer',
  'Prof. Stefan Eber',
  'Prof. Stefan Eber',
  'Dr. Reinhard Erdl',
  'Dr. Reinhard Erdl',
  'Dr. Linda Johnston-Rohrbasser',
  'Dr. Linda Johnston-Rohrbasser',
  'Dieter Hammel',
  'Dieter Hammel',
  'Rainer Hambrecht',
  'Rainer Hambrecht',
  'Martin Claßen',
  'Martin Claßen',
  'Alessandro Marra',
  'Alessandro Marra',
  'Gabor Gaebel',
  'Gabor Gaebel',
  'Thomas Haarmeier',
  'Thomas Haarmeier',
  'Michael Friedrich',
  'Michael Friedrich',
  'Dieter Ukena',
  'Dieter Ukena',
  'Christian Molleken',
  'Christian Molleken',
  'Rainer Porschen',
  'Rainer Porschen',
  'Birgit Kauffmann',
  'Birgit Kauffmann',
  'Heiner Wenk',
  'Heiner Wenk',
  'Wladimir Pauker',
  'Wladimir Pauker',
  'Saskia Biskup',
  'Saskia Biskup',
  'Takahiro Moriyama',
  'Takahiro Moriyama',
  'Dirk Pajonk',
  'Dirk Pajonk',
  'Uve Niksdoff',
  'Uve Niksdoff',
  'Dirk Schadendorf',
  'Dirk Schadendorf',
  'Peter Reimer',
  'Peter Reimer',
  'Reiner Haas',
  'Reiner Haas',
  'Carsten Perka',
  'Carsten Perka',
  'Robert Thimme',
  'Robert Thimme',
  'Ulrich Vetteraurer',
  'Ulrich Vetteraurer',
  'Ernst-Johannes Haberl',
  'Ernst-Johannes Haberl',
  'Gerd-Rüdiger Burmester',
  'Gerd-Rüdiger Burmester',
  'Andreas Greiner',
  'Andreas Greiner',
  'Angelika Eggert',
  'Angelika Eggert',
  'Veit Hofmann',
  'Veit Hofmann',
  'Antonio Pezzutto',
  'Antonio Pezzutto',
  'Friedhelm Beyersdorf',
  'Friedhelm Beyersdorf',
  'Walter Zidek',
  'Walter Zidek',
  'Ulf Landmesser',
  'Ulf Landmesser',
  'Ulrike Blume-Peytavi',
  'Ulrike Blume-Peytavi',
  'Jalid Sehouli',
  'Jalid Sehouli',
  'Britta Siegmund',
  'Britta Siegmund',
  'Antonia Joussen',
  'Antonia Joussen',
  'Michael Schütz',
  'Michael Schütz',
  'Volker Budach',
  'Volker Budach',
  'Gerald Gitsch',
  'Gerald Gitsch',
  'Josef Zentner',
  'Josef Zentner',
  'Mahdi Rezai',
  'Mahdi Rezai',
  'Philipp Wiehle',
  'Philipp Wiehle',
  'Thomas Kaleta',
  'Thomas Kaleta',
  'Anne-Sophie Vesper',
  'Anne-Sophie Vesper',
  'Jurgen Hoffmann',
  'Jurgen Hoffmann',
  'Andreas Schulze-Bonhage',
  'Andreas Schulze-Bonhage',
  'Uwe A Wittel',
  'Uwe A Wittel',
  'Stefan Fichtner-Feigl',
  'Stefan Fichtner-Feigl',
  'Charlotte Niemeyer',
  'Charlotte Niemeyer',
  'Cornelius Waller',
  'Cornelius Waller',
  'Christian Winkler',
  'Christian Winkler',
  'Justus Duyster',
  'Justus Duyster',
  'Jan-Helge Klingler',
  'Jan-Helge Klingler',
  'Ulrich Hubbe',
  'Ulrich Hubbe',
  'Frank Meiß',
  'Frank Meiß',
  'Ulrich Theodor Hopt',
  'Ulrich Theodor Hopt',
  'Christian Leiber',
  'Christian Leiber',
  'Philipp T. Meyer',
  'Philipp T. Meyer',
  'Anca-Ligia Grosu',
  'Anca-Ligia Grosu',
  'Oliver Schnell',
  'Oliver Schnell',
  'Kurt Miller',
  'Kurt Miller',
  'Ulrich Keilholz',
  'Ulrich Keilholz',
  'Peter Vajkoczy',
  'Peter Vajkoczy',
  'Matthias Endres',
  'Matthias Endres',
  'Markus Kufeld',
  'Markus Kufeld',
  'Christian Witt',
  'Christian Witt',
  'Johann Pratschke',
  'Johann Pratschke',
  'Christian Grah',
  'Christian Grah',
  'Michael Schenk',
  'Michael Schenk',
  'Patricia Dé-Malter',
  'Patricia Dé-Malter',
  'Hans-Peter Lemmens',
  'Hans-Peter Lemmens',
  'Friedemann Schad',
  'Friedemann Schad',
  'Engin Osmanoglou',
  'Engin Osmanoglou',
  'Martin Strik',
  'Martin Strik',
  'Kerstin Lommel',
  'Kerstin Lommel',
  'Per-ulf Tunn',
  'Per-ulf Tunn',
  'Frank Kolligs',
  'Frank Kolligs',
  'Peter Reichardt',
  'Peter Reichardt',
  'Daniel Kendoff',
  'Daniel Kendoff',
  'Miklos Hamori',
  'Miklos Hamori',
  'Georg Hagemann',
  'Georg Hagemann',
  'Gerd Friedrich Westphal',
  'Gerd Friedrich Westphal',
  'Horst Glasner',
  'Horst Glasner',
  'Mark Hartel',
  'Mark Hartel',
  'Michael Heike',
  'Michael Heike',
  'Dennis Prokofiev',
  'Dennis Prokofiev',
  'Niklas Kreutzer',
  'Niklas Kreutzer',
  'Michael Truss',
  'Michael Truss',
  'Heribert Kentenich',
  'Heribert Kentenich',
  'Andreas Tandler-Schneider',
  'Andreas Tandler-Schneider',
  'Jan-Michel Otte',
  'Jan-Michel Otte',
  'Felix Berger',
  'Felix Berger',
  'Ihab. El-Bably',
  'Ihab. El-Bably',
  'Manfred Tetz',
  'Manfred Tetz',
  'Basem Alabud',
  'Basem Alabud',
  'Ursula Makowiec',
  'Ursula Makowiec',
  'Ulrich Böhling',
  'Ulrich Böhling',
  'Theodoros Kombos',
  'Theodoros Kombos',
  'Willibald Walter',
  'Willibald Walter'],
 ['Medical Center in Solingen',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Nord Clinic',
  'Asklepios Hospital Barmbek',
  'Medical Center in Solingen',
  'Nordwest Clinic (Krankenhaus)',
  'Medical Center in Solingen',
  'Asklepios Hospital Barmbek',
  'Sachsenhausen Hospital',
  'Medical Center in Solingen',
  'Nordwest Clinic (Krankenhaus)',
  'Asklepios St. Georg Hospital',
  'Asklepios Hospital Barmbek',
  'Nordwest Clinic (Krankenhaus)',
  'Medical Center in Solingen',
  'Medical Center in Solingen',
  'Asklepios St. Georg Hospital',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Asklepios Hospital Barmbek',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Asklepios Altona Clinic',
  "Eye Surgeries Professor Schaller's Private Practice in Eye Clinic of Herzog Carl Theodor-Munich",
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Sachsenhausen Hospital',
  'Asklepios St. Georg Hospital',
  'Asklepios St. Georg Hospital',
  'Radiology Munich',
  'Asklepios Hospital Barmbek',
  'St. Martinus-Krankenhaus Düsseldorf',
  'Asklepios St. Georg Hospital',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Nordwest Clinic (Krankenhaus)',
  'Medical Center in Solingen',
  'Medical Center in Solingen',
  'Medical Center in Solingen',
  'Düsseldorf Clinics Association',
  'Asklepios Altona Clinic',
  'Asklepios St. Georg Hospital',
  'Medical Center in Solingen',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Sachsenhausen Hospital',
  'Düsseldorf Clinics Association',
  'Düsseldorf Clinics Association',
  'Düsseldorf Clinics Association',
  'Düsseldorf Clinics Association',
  'Düsseldorf Clinics Association',
  'Düsseldorf Clinics Association',
  'Asklepios St. Georg Hospital',
  'Asklepios St. Georg Hospital',
  'Asklepios St. Georg Hospital',
  'Asklepios Nord Clinic',
  'Asklepios Nord Clinic',
  'Asklepios Nord Clinic',
  'Asklepios Nord Clinic',
  'Asklepios Altona Clinic',
  'Asklepios Altona Clinic',
  'Asklepios Altona Clinic',
  'Medical Center in Solingen',
  'Medical Center in Solingen',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Asklepios Hospital Barmbek',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Nordwest Clinic (Krankenhaus)',
  'Asklepios Hospital Barmbek',
  'Nordrhein-Westfalen Clinic Complex',
  'Nordrhein-Westfalen Clinic Complex',
  'Nordrhein-Westfalen Clinic Complex',
  'Nordrhein-Westfalen Clinic Complex',
  'Meoclinic Hospital',
  'EuroEyes Clinic',
  'Helios Hospital Krefeld',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Privatpraxis Vosspalais',
  'Privatpraxis Vosspalais',
  'Privatpraxis Vosspalais',
  'Bremen-Mitte Clinic',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Krefeld',
  'Links der Weser Clinic',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Bremen-Mitte Clinic',
  'PRADUS Diagnostics',
  'Helios Hospital Krefeld',
  'Marianowicz Diagnosis & Therapy Centre',
  'Helios Hospital Krefeld',
  'Bethanien Clinic',
  'Helios Hospital Berlin Buch',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Bremen-Mitte Clinic',
  'Prostate Center Europe',
  'Zentrum der Rehabilitation Pforzheim',
  'Essen University Hospital',
  'Essen University Hospital',
  'Essen University Hospital',
  'Essen University Hospital',
  'Zentrum der Rehabilitation Pforzheim',
  'Zentrum der Rehabilitation Pforzheim',
  'Frankfurter Rotkreuz-Kliniken (Frankfurt Red Cross Hospital)',
  'Alfried Krupp Krankenhaus',
  'Dermatologikum Berlin',
  'Dermatologikum Berlin',
  'Dermatologikum Berlin',
  'Dermatologikum Berlin',
  'Dermatologikum Berlin',
  'Essen University Hospital',
  'Lippe Lemgo Clinic',
  'Lippe Lemgo Clinic',
  'Lippe Detmold Clinic',
  'Lippe Detmold Clinic',
  'Lippe Detmold Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'Links der Weser Clinic',
  'Links der Weser Clinic',
  'Links der Weser Clinic',
  'Bremen-Ost Clinic',
  'Helios Hospital Krefeld',
  'Helios Hospital Krefeld',
  'Helios Hospital Krefeld',
  'Bremen-Ost Clinic',
  'PRADUS Diagnostics',
  'Bremen-Ost Clinic',
  'Bremen-Nord Clinic',
  'Bremen-Nord Clinic',
  'Bremen-Nord Clinic',
  'PRADUS Diagnostics',
  'PRADUS Diagnostics',
  'PRADUS Diagnostics',
  'PRADUS Diagnostics',
  'Essen University Hospital',
  'Essen University Hospital',
  'The University Hospital in Dusseldorf',
  'Charité - Universitätsmedizin Berlin',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'The University Hospital in Dusseldorf',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'The University Hospital in Dusseldorf',
  'The University Hospital in Dusseldorf',
  'The University Hospital in Dusseldorf',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Medical Center - University of Freiburg (Uniklinik Freiburg)',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Charité - Universitätsmedizin Berlin',
  'Hospital Havelhoehe',
  'Hospital Havelhoehe',
  'Hospital Havelhoehe',
  'Hospital Havelhoehe',
  'Hospital Havelhoehe',
  'Meoclinic Hospital',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Helios Hospital Berlin Buch',
  'Fertility Center Erlangen',
  'Helios Hospital Berlin Buch',
  'Meoclinic Hospital',
  'Meoclinic Hospital',
  'Department of Urology at Dortmund Clinic',
  'Department of Urology at Dortmund Clinic',
  'Department of Urology at Dortmund Clinic',
  'Department of Urology at Dortmund Clinic',
  'Department of Urology at Dortmund Clinic',
  'Fertility Center Berlin',
  'Fertility Center Berlin',
  'DRK Clinic Berlin',
  'Deutsches Herzzentrum Berlin',
  'Spreebogen Ophthalmology Clinic',
  'Spreebogen Ophthalmology Clinic',
  'Urologie Boeblingen',
  'Schlosspark Clinic',
  'Schlosspark Clinic',
  'Schlosspark Clinic',
  'Marianowicz Diagnosis & Therapy Centre'])

In [197]:
# Use Counter to count occurrences of each unique doctor name
from collections import Counter   
Counter(y[0])

Counter({'Uta Meyding-Lamade': 4,
         'Jörg B. Engel': 4,
         'Ralf Buhl': 2,
         'Andreas Gross': 2,
         'Peter Paul Urban': 2,
         'Paul Kremer': 2,
         'Ulrich Schaudig': 2,
         'Boris Pfaffenbach': 2,
         'Elke Jaeger': 2,
         'Sasсha Flohé': 2,
         'Karl J. Oldhafer': 2,
         'Plamen Staikov': 2,
         'Andreas Sesterhenn': 2,
         'Siegbert Rossol': 2,
         'Ahmet Elmaagacli': 2,
         'Gerhard Gebauer': 2,
         'Eckhart Weidmann': 2,
         'Manuela Seifert': 2,
         'Marcus Goyzer': 2,
         'Jens E. Meyer': 2,
         'Axel Stang': 2,
         'Stefanie Veit': 2,
         'Uwe Kehler': 2,
         'Ulrich Schaller': 2,
         'Christoph Rangger': 2,
         'Thomas W Kraus': 2,
         'Peter Ulrich': 2,
         'Michael Van Kampen': 2,
         'Philipp-Andreas Hessler': 2,
         'Ulrich-Frank Pape': 2,
         'Christian Sander': 2,
         'Prof Dr Hendrik Wolff': 2,
         'Jorn Halberstadt': 2,
         'Matthias Schlensak': 2,
         'Stephan Willems': 2,
         'Bodo Lippitz': 2,
         'Antje-Katrin Hofele': 2,
         'Sven Rogmans': 2,
         'Peter Schenker': 2,
         'Marcel Dihne': 2,
         'Phd Viola Fox': 2,
         'Kristyan Vaik': 2,
         'Christian Wülfing': 2,
         'Michael Hoffmann': 2,
         'Sven Propson': 2,
         'Jurgen Stein': 2,
         'Holger Bahn': 2,
         'Konrad Stubbig': 2,
         'Arun Kumarasamy': 2,
         'Claudius Teupe': 2,
         'Ralf Jung': 2,
         'Anke Reitter': 2,
         'Ralf Kolvenbach': 2,
         'Wolfgang Nebelung': 2,
         'Rolf Michael Klein': 2,
         'Wolfgang Steinke': 2,
         'Yorg Herdmann': 2,
         'Aristoteles Giagonidis': 2,
         'Michael Schmoeckel': 2,
         'Gerd Manthei': 2,
         'Silke Tribius': 2,
         'Holger Maul': 2,
         'Bernd Schroeder': 2,
         'Hita Tushar Dave': 2,
         'Guenter Seidel': 2,
         'Thomas Grundmann': 2,
         'Detlef Rose': 2,
         'Juergen Pohl': 2,
         'Sebastian Keil': 2,
         'Martin Peters': 2,
         'Petra Reemts': 2,
         'Norbert Schmitz': 2,
         'Klaus D. Diemel': 2,
         'Axel Hillmann': 2,
         'Agoritsa Stergiou-Tsaroucha': 2,
         'Veit Becker': 2,
         'Juergen Faiss': 2,
         'Stefan Schreiber': 2,
         'Thomas Mansfeld': 2,
         'Johann Pichl': 2,
         'Thomas Carus': 2,
         'Thomas Verse': 2,
         'Henrik Becker': 2,
         'Milan Lisy': 2,
         'Markus Düx': 2,
         'Matthias W. Lorenz': 2,
         'Gerhart Tseslinsky': 2,
         'Max Zegelman': 2,
         'Eduard Becht': 2,
         'Gunther Wiest': 2,
         'Jorg Handschel': 2,
         'Garald Krentel': 2,
         'Jan Fichtner': 2,
         'Gerd Degoutrie': 2,
         'Jürgen Kiwit': 2,
         'Jorn Jorgensen': 2,
         'Clayton Kraft': 2,
         'Michael Unch': 2,
         'Bertram Glaß': 2,
         'Professor Volker Budach': 2,
         'Doctor Maria Steingraber': 2,
         'Professor Simone Marnitz': 2,
         'Sebastian Melchior': 2,
         'Mark Schrader': 2,
         'Jaroslav Benedik': 2,
         'Carsten Michael Oberhoff': 2,
         'Stefan Dresel': 2,
         'Robert Krempien': 2,
         'Jorg Groticke': 2,
         'Ludger Wilhelm Poll': 2,
         'Martin Friedrich': 2,
         'Martin Marianowicz': 2,
         'Michael Stoffel': 2,
         'Markus Heuser': 2,
         'Yu-mi Ryang': 2,
         'Huseyin Bektas': 2,
         'Bernd Hertenstein': 2,
         'Markus Zutt': 2,
         'Arne-Joern Lemke': 2,
         'Erik Chankiewitz': 2,
         'Andreas Schuler': 2,
         'Andreas Kastrup': 2,
         'Klaus Luque': 2,
         'Mustafa Aydogdu': 2,
         'Johann Ockenga': 2,
         'Jan Korde': 2,
         'Krystyna Wisniewski': 2,
         'Michael Paul Hahn': 2,
         'Andreas Naumann': 2,
         'Uwe Neubauer': 2,
         'Jоrn H. Witt': 2,
         'Marco Dorshner': 2,
         'Guido Gerken': 2,
         'Martin Stuschke': 2,
         'Andreas Hufnagel': 2,
         'Dietrich W. Beelen': 2,
         'Daniela Dorshner-Gerlofs': 2,
         'Ruud Gerlofs': 2,
         'Human Zafiarian': 2,
         'Roland Veltkamp': 2,
         'Kristian Reich': 2,
         'Volker Steinkraus': 2,
         'L. Rainer Rupprecht': 2,
         'Eckhart Kämpgen': 2,
         'Uwe Trefzer': 2,
         'Christoph Kleinschnitz': 2,
         'Ulrich Schäfer': 2,
         'Frank Hartmann': 2,
         'Cyrus Klostermann': 2,
         'Stephan Gielen': 2,
         'Wolfgang Hiller': 2,
         'Dr. Marion Eckert': 2,
         'Prof. Uwe Mellies': 2,
         'Prof. Heiko Stern': 2,
         'Dr. Simon Mayer': 2,
         'Prof. Stefan Eber': 2,
         'Dr. Reinhard Erdl': 2,
         'Dr. Linda Johnston-Rohrbasser': 2,
         'Dieter Hammel': 2,
         'Rainer Hambrecht': 2,
         'Martin Claßen': 2,
         'Alessandro Marra': 2,
         'Gabor Gaebel': 2,
         'Thomas Haarmeier': 2,
         'Michael Friedrich': 2,
         'Dieter Ukena': 2,
         'Christian Molleken': 2,
         'Rainer Porschen': 2,
         'Birgit Kauffmann': 2,
         'Heiner Wenk': 2,
         'Wladimir Pauker': 2,
         'Saskia Biskup': 2,
         'Takahiro Moriyama': 2,
         'Dirk Pajonk': 2,
         'Uve Niksdoff': 2,
         'Dirk Schadendorf': 2,
         'Peter Reimer': 2,
         'Reiner Haas': 2,
         'Carsten Perka': 2,
         'Robert Thimme': 2,
         'Ulrich Vetteraurer': 2,
         'Ernst-Johannes Haberl': 2,
         'Gerd-Rüdiger Burmester': 2,
         'Andreas Greiner': 2,
         'Angelika Eggert': 2,
         'Veit Hofmann': 2,
         'Antonio Pezzutto': 2,
         'Friedhelm Beyersdorf': 2,
         'Walter Zidek': 2,
         'Ulf Landmesser': 2,
         'Ulrike Blume-Peytavi': 2,
         'Jalid Sehouli': 2,
         'Britta Siegmund': 2,
         'Antonia Joussen': 2,
         'Michael Schütz': 2,
         'Volker Budach': 2,
         'Gerald Gitsch': 2,
         'Josef Zentner': 2,
         'Mahdi Rezai': 2,
         'Philipp Wiehle': 2,
         'Thomas Kaleta': 2,
         'Anne-Sophie Vesper': 2,
         'Jurgen Hoffmann': 2,
         'Andreas Schulze-Bonhage': 2,
         'Uwe A Wittel': 2,
         'Stefan Fichtner-Feigl': 2,
         'Charlotte Niemeyer': 2,
         'Cornelius Waller': 2,
         'Christian Winkler': 2,
         'Justus Duyster': 2,
         'Jan-Helge Klingler': 2,
         'Ulrich Hubbe': 2,
         'Frank Meiß': 2,
         'Ulrich Theodor Hopt': 2,
         'Christian Leiber': 2,
         'Philipp T. Meyer': 2,
         'Anca-Ligia Grosu': 2,
         'Oliver Schnell': 2,
         'Kurt Miller': 2,
         'Ulrich Keilholz': 2,
         'Peter Vajkoczy': 2,
         'Matthias Endres': 2,
         'Markus Kufeld': 2,
         'Christian Witt': 2,
         'Johann Pratschke': 2,
         'Christian Grah': 2,
         'Michael Schenk': 2,
         'Patricia Dé-Malter': 2,
         'Hans-Peter Lemmens': 2,
         'Friedemann Schad': 2,
         'Engin Osmanoglou': 2,
         'Martin Strik': 2,
         'Kerstin Lommel': 2,
         'Per-ulf Tunn': 2,
         'Frank Kolligs': 2,
         'Peter Reichardt': 2,
         'Daniel Kendoff': 2,
         'Miklos Hamori': 2,
         'Georg Hagemann': 2,
         'Gerd Friedrich Westphal': 2,
         'Horst Glasner': 2,
         'Mark Hartel': 2,
         'Michael Heike': 2,
         'Dennis Prokofiev': 2,
         'Niklas Kreutzer': 2,
         'Michael Truss': 2,
         'Heribert Kentenich': 2,
         'Andreas Tandler-Schneider': 2,
         'Jan-Michel Otte': 2,
         'Felix Berger': 2,
         'Ihab. El-Bably': 2,
         'Manfred Tetz': 2,
         'Basem Alabud': 2,
         'Ursula Makowiec': 2,
         'Ulrich Böhling': 2,
         'Theodoros Kombos': 2,
         'Willibald Walter': 2})

In [195]:
#total length of y[0] is 518
len(y[0])

518

In [279]:
# The issue with the length of doctor names and clinic addresses is addressed here. 
#when I am doing len(set(y[0])) I am getting length 257, which is two less than length of len(y[1]) so it will create a problem when forming a dataframe.
# We filter the 'a' list to only include names at odd indices. 
l=[]   # Initialize an empty list
for i in range(1,519):  #This loop iterates up to 519, assuming it's the total number of names in your data
    if i%2!=0:  # Only append names at odd indices
        l.append(y[0][i])
l

['Ralf Buhl',
 'Andreas Gross',
 'Peter Paul Urban',
 'Paul Kremer',
 'Ulrich Schaudig',
 'Boris Pfaffenbach',
 'Elke Jaeger',
 'Sasсha Flohé',
 'Karl J. Oldhafer',
 'Plamen Staikov',
 'Andreas Sesterhenn',
 'Siegbert Rossol',
 'Ahmet Elmaagacli',
 'Gerhard Gebauer',
 'Eckhart Weidmann',
 'Manuela Seifert',
 'Marcus Goyzer',
 'Jens E. Meyer',
 'Uta Meyding-Lamade',
 'Jörg B. Engel',
 'Axel Stang',
 'Stefanie Veit',
 'Jörg B. Engel',
 'Uta Meyding-Lamade',
 'Uwe Kehler',
 'Ulrich Schaller',
 'Christoph Rangger',
 'Thomas W Kraus',
 'Peter Ulrich',
 'Michael Van Kampen',
 'Philipp-Andreas Hessler',
 'Ulrich-Frank Pape',
 'Christian Sander',
 'Prof Dr Hendrik Wolff',
 'Jorn Halberstadt',
 'Matthias Schlensak',
 'Stephan Willems',
 'Bodo Lippitz',
 'Antje-Katrin Hofele',
 'Sven Rogmans',
 'Peter Schenker',
 'Marcel Dihne',
 'Phd Viola Fox',
 'Kristyan Vaik',
 'Christian Wülfing',
 'Michael Hoffmann',
 'Sven Propson',
 'Jurgen Stein',
 'Holger Bahn',
 'Konrad Stubbig',
 'Arun Kumarasamy',
 'Claudius Teupe',
 'Ralf Jung',
 'Anke Reitter',
 'Ralf Kolvenbach',
 'Wolfgang Nebelung',
 'Rolf Michael Klein',
 'Wolfgang Steinke',
 'Yorg Herdmann',
 'Aristoteles Giagonidis',
 'Michael Schmoeckel',
 'Gerd Manthei',
 'Silke Tribius',
 'Holger Maul',
 'Bernd Schroeder',
 'Hita Tushar Dave',
 'Guenter Seidel',
 'Thomas Grundmann',
 'Detlef Rose',
 'Juergen Pohl',
 'Sebastian Keil',
 'Martin Peters',
 'Petra Reemts',
 'Norbert Schmitz',
 'Klaus D. Diemel',
 'Axel Hillmann',
 'Agoritsa Stergiou-Tsaroucha',
 'Veit Becker',
 'Juergen Faiss',
 'Stefan Schreiber',
 'Thomas Mansfeld',
 'Johann Pichl',
 'Thomas Carus',
 'Thomas Verse',
 'Henrik Becker',
 'Milan Lisy',
 'Markus Düx',
 'Matthias W. Lorenz',
 'Gerhart Tseslinsky',
 'Max Zegelman',
 'Eduard Becht',
 'Gunther Wiest',
 'Jorg Handschel',
 'Garald Krentel',
 'Jan Fichtner',
 'Gerd Degoutrie',
 'Jürgen Kiwit',
 'Jorn Jorgensen',
 'Clayton Kraft',
 'Michael Unch',
 'Bertram Glaß',
 'Professor Volker Budach',
 'Doctor Maria Steingraber',
 'Professor Simone Marnitz',
 'Sebastian Melchior',
 'Mark Schrader',
 'Jaroslav Benedik',
 'Carsten Michael Oberhoff',
 'Stefan Dresel',
 'Robert Krempien',
 'Jorg Groticke',
 'Ludger Wilhelm Poll',
 'Martin Friedrich',
 'Martin Marianowicz',
 'Michael Stoffel',
 'Markus Heuser',
 'Yu-mi Ryang',
 'Huseyin Bektas',
 'Bernd Hertenstein',
 'Markus Zutt',
 'Arne-Joern Lemke',
 'Erik Chankiewitz',
 'Andreas Schuler',
 'Andreas Kastrup',
 'Klaus Luque',
 'Mustafa Aydogdu',
 'Johann Ockenga',
 'Jan Korde',
 'Krystyna Wisniewski',
 'Michael Paul Hahn',
 'Andreas Naumann',
 'Uwe Neubauer',
 'Jоrn H. Witt',
 'Marco Dorshner',
 'Guido Gerken',
 'Martin Stuschke',
 'Andreas Hufnagel',
 'Dietrich W. Beelen',
 'Daniela Dorshner-Gerlofs',
 'Ruud Gerlofs',
 'Human Zafiarian',
 'Roland Veltkamp',
 'Kristian Reich',
 'Volker Steinkraus',
 'L. Rainer Rupprecht',
 'Eckhart Kämpgen',
 'Uwe Trefzer',
 'Christoph Kleinschnitz',
 'Ulrich Schäfer',
 'Frank Hartmann',
 'Cyrus Klostermann',
 'Stephan Gielen',
 'Wolfgang Hiller',
 'Dr. Marion Eckert',
 'Prof. Uwe Mellies',
 'Prof. Heiko Stern',
 'Dr. Simon Mayer',
 'Prof. Stefan Eber',
 'Dr. Reinhard Erdl',
 'Dr. Linda Johnston-Rohrbasser',
 'Dieter Hammel',
 'Rainer Hambrecht',
 'Martin Claßen',
 'Alessandro Marra',
 'Gabor Gaebel',
 'Thomas Haarmeier',
 'Michael Friedrich',
 'Dieter Ukena',
 'Christian Molleken',
 'Rainer Porschen',
 'Birgit Kauffmann',
 'Heiner Wenk',
 'Wladimir Pauker',
 'Saskia Biskup',
 'Takahiro Moriyama',
 'Dirk Pajonk',
 'Uve Niksdoff',
 'Dirk Schadendorf',
 'Peter Reimer',
 'Reiner Haas',
 'Carsten Perka',
 'Robert Thimme',
 'Ulrich Vetteraurer',
 'Ernst-Johannes Haberl',
 'Gerd-Rüdiger Burmester',
 'Andreas Greiner',
 'Angelika Eggert',
 'Veit Hofmann',
 'Antonio Pezzutto',
 'Friedhelm Beyersdorf',
 'Walter Zidek',
 'Ulf Landmesser',
 'Ulrike Blume-Peytavi',
 'Jalid Sehouli',
 'Britta Siegmund',
 'Antonia Joussen',
 'Michael Schütz',
 'Volker Budach',
 'Gerald Gitsch',
 'Josef Zentner',
 'Mahdi Rezai',
 'Philipp Wiehle',
 'Thomas Kaleta',
 'Anne-Sophie Vesper',
 'Jurgen Hoffmann',
 'Andreas Schulze-Bonhage',
 'Uwe A Wittel',
 'Stefan Fichtner-Feigl',
 'Charlotte Niemeyer',
 'Cornelius Waller',
 'Christian Winkler',
 'Justus Duyster',
 'Jan-Helge Klingler',
 'Ulrich Hubbe',
 'Frank Meiß',
 'Ulrich Theodor Hopt',
 'Christian Leiber',
 'Philipp T. Meyer',
 'Anca-Ligia Grosu',
 'Oliver Schnell',
 'Kurt Miller',
 'Ulrich Keilholz',
 'Peter Vajkoczy',
 'Matthias Endres',
 'Markus Kufeld',
 'Christian Witt',
 'Johann Pratschke',
 'Christian Grah',
 'Michael Schenk',
 'Patricia Dé-Malter',
 'Hans-Peter Lemmens',
 'Friedemann Schad',
 'Engin Osmanoglou',
 'Martin Strik',
 'Kerstin Lommel',
 'Per-ulf Tunn',
 'Frank Kolligs',
 'Peter Reichardt',
 'Daniel Kendoff',
 'Miklos Hamori',
 'Georg Hagemann',
 'Gerd Friedrich Westphal',
 'Horst Glasner',
 'Mark Hartel',
 'Michael Heike',
 'Dennis Prokofiev',
 'Niklas Kreutzer',
 'Michael Truss',
 'Heribert Kentenich',
 'Andreas Tandler-Schneider',
 'Jan-Michel Otte',
 'Felix Berger',
 'Ihab. El-Bably',
 'Manfred Tetz',
 'Basem Alabud',
 'Ursula Makowiec',
 'Ulrich Böhling',
 'Theodoros Kombos',
 'Willibald Walter']

In [203]:
len(l)  # Check the length of the filtered list

259

In [189]:
len(y[1])  # Check the length of the clinic address list

259

In [205]:
# Create DataFrames from the extracted lists
df1=pd.DataFrame(l)  # DataFrame for doctor names
df1

                    0
0           Ralf Buhl
1       Andreas Gross
2    Peter Paul Urban
3         Paul Kremer
4     Ulrich Schaudig
..                ...
254      Basem Alabud
255   Ursula Makowiec
256    Ulrich Böhling
257  Theodoros Kombos
258  Willibald Walter

[259 rows x 1 columns]

In [207]:
df2=pd.DataFrame(y[1])  # DataFrame for clinic addresses
df2

                                          0
0                Medical Center in Solingen
1                Asklepios Hospital Barmbek
2                Asklepios Hospital Barmbek
3                     Asklepios Nord Clinic
4                Asklepios Hospital Barmbek
..                                      ...
254                     Urologie Boeblingen
255                      Schlosspark Clinic
256                      Schlosspark Clinic
257                      Schlosspark Clinic
258  Marianowicz Diagnosis & Therapy Centre

[259 rows x 1 columns]

In [209]:
combined_column = pd.concat([df1,df2], axis=1)   # Combine the two DataFrames vertically
print(combined_column)

                    0                                       0
0           Ralf Buhl              Medical Center in Solingen
1       Andreas Gross              Asklepios Hospital Barmbek
2    Peter Paul Urban              Asklepios Hospital Barmbek
3         Paul Kremer                   Asklepios Nord Clinic
4     Ulrich Schaudig              Asklepios Hospital Barmbek
..                ...                                     ...
254      Basem Alabud                     Urologie Boeblingen
255   Ursula Makowiec                      Schlosspark Clinic
256    Ulrich Böhling                      Schlosspark Clinic
257  Theodoros Kombos                      Schlosspark Clinic
258  Willibald Walter  Marianowicz Diagnosis & Therapy Centre

[259 rows x 2 columns]

In [211]:
combined_column.columns=["Name","Address"]  # Assign column names

In [213]:
combined_column

                 Name                                 Address
0           Ralf Buhl              Medical Center in Solingen
1       Andreas Gross              Asklepios Hospital Barmbek
2    Peter Paul Urban              Asklepios Hospital Barmbek
3         Paul Kremer                   Asklepios Nord Clinic
4     Ulrich Schaudig              Asklepios Hospital Barmbek
..                ...                                     ...
254      Basem Alabud                     Urologie Boeblingen
255   Ursula Makowiec                      Schlosspark Clinic
256    Ulrich Böhling                      Schlosspark Clinic
257  Theodoros Kombos                      Schlosspark Clinic
258  Willibald Walter  Marianowicz Diagnosis & Therapy Centre

[259 rows x 2 columns]

In [155]:
y=[]
p=[]
w=[]
# Define a function to extract doctor names and clinic addresses from clinicsoncall.com

def function(webpage):   # Create a BeautifulSoup object to parse the HTML
    soup=BeautifulSoup(webpage,'lxml')

    # Find all 'h2' tags with the class 'doctor-name'
    for i in soup.find_all('h2',class_='doctor-name'):
        y.append(i.text.strip())  # Append the cleaned doctor name to the 'y' list

    # Find all 'div' tags with the class 'doctor-info-text'

    for i in soup.find_all('div',class_='doctor-info-text'):
        p.append(i.text.strip())   # Append the cleaned text content to the 'p' 
    # Return both lists containing extracted data
    return y,p

# Set headers to mimic a regular browser request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
# Loop through multiple pages of the website
for i in range(1,15):
    # Construct the URL for each page
    webpage=requests.get(f'https://clinicsoncall.com/en/doctors/country-germany/page/{i}/',headers=headers).text  # Fetch HTML content of the page
    x=function(webpage)   # Call the 'function' function to extract data from the page

#print(x[0])
# Extract the first line from each 'div' tag in the 'p' list
for i in x[1]:
    w.append(i.split('\n')[0])  # Append the first line (presumably the address) to the 'w' list


#w

In [157]:
# Create DataFrames for the extracted data
df=pd.DataFrame(x[0])   # DataFrame for doctor names
df

                                  0
0    Prof. Dr. Klaus Dieter Schaser
1               Dr. Wolfgang Böcker
2            Prof. Dr. Barbara Carl
3                 Dr. Zoltan Derzsy
4               Dr. Rainer Ruprecht
..                              ...
261        Prof. Dr. Peter Mallmann
262         Prof. Dr. Rüdiger Lange
263             Dr. Robert Krempien
264       Prof. Dr. Rudiger Gerlach
265      Prof. Dr. Joachim Fotiadis

[266 rows x 1 columns]

In [159]:
df1=pd.DataFrame(w)   # DataFrame for clinic addresses
df1

                                                     0
0         Clinic University Hospital Carl Gustav Carus
1    Clinic Ludwig Maximilian University Hospital M...
2    Clinic Helios Dr. Horst Schmidt Kliniken Wiesb...
3                     Clinic Helios Hospital Pforzheim
4                         Clinic Dermatologikum Berlin
..                                                 ...
261                 Clinic University Hospital Cologne
262                  Clinic German Heart Center Munich
263                 Clinic Helios Berlin-Buch Hospital
264                      Clinic Helios Hospital Erfurt
265                  Clinic German Heart Center Munich

[266 rows x 1 columns]

In [161]:
combined_output=pd.concat([df,df1],axis=1)  # Combine the two DataFrames vertically
combined_output

,0,0
0,Prof. Dr. Klaus Dieter Schaser,Clinic University Hospital Carl Gustav Carus
1,Dr. Wolfgang Böcker,Clinic Ludwig Maximilian University Hospital M...
2,Prof. Dr. Barbara Carl,Clinic Helios Dr. Horst Schmidt Kliniken Wiesb...
3,Dr. Zoltan Derzsy,Clinic Helios Hospital Pforzheim
4,Dr. Rainer Ruprecht,Clinic Dermatologikum Berlin
...,...,...
261,Prof. Dr. Peter Mallmann,Clinic University Hospital Cologne
262,Prof. Dr. Rüdiger Lange,Clinic German Heart Center Munich
263,Dr. Robert Krempien,Clinic Helios Berlin-Buch Hospital
264,Prof. Dr. Rudiger Gerlach,Clinic Helios Hospital Erfurt
265,Prof. Dr. Joachim Fotiadis,Clinic German Heart Center Munich

In [167]:
combined_output.columns=["Name","Address"]  # Assign column names
combined_output

,Name,Address
0,Prof. Dr. Klaus Dieter Schaser,Clinic University Hospital Carl Gustav Carus
1,Dr. Wolfgang Böcker,Clinic Ludwig Maximilian University Hospital M...
2,Prof. Dr. Barbara Carl,Clinic Helios Dr. Horst Schmidt Kliniken Wiesb...
3,Dr. Zoltan Derzsy,Clinic Helios Hospital Pforzheim
4,Dr. Rainer Ruprecht,Clinic Dermatologikum Berlin
...,...,...
261,Prof. Dr. Peter Mallmann,Clinic University Hospital Cologne
262,Prof. Dr. Rüdiger Lange,Clinic German Heart Center Munich
263,Dr. Robert Krempien,Clinic Helios Berlin-Buch Hospital
264,Prof. Dr. Rudiger Gerlach,Clinic Helios Hospital Erfurt
265,Prof. Dr. Joachim Fotiadis,Clinic German Heart Center Munich

In [263]:
a=[]   # Initialize an empty list named 'a' to store doctor names
d=[]  # Initialize an empty list named 'd' to store clinic addresses
t=[]  # Initialize an empty list named 't' to store filtered doctor names

# Define a function named 'funvalue' that takes a webpage as input
def funvalue(webpage):
    soup=BeautifulSoup(webpage,'lxml')  # Create a BeautifulSoup object to parse the HTML content of the webpage
    for i in soup.find_all('a',class_='doctor-card__name'):  # Find all 'a' tags with the class 'doctor-card__name' within the HTML
        a.append(i.text.strip())  # Append the cleaned text content of each 'a' tag (doctor name) to the 'a' list
    #r=list(set(a))
    #when I am doing len(set(a)),I am able to get unique elements but it is not sorting in the same order as the values in list d so I have choosen the below method.
    for i in range(len(a)):  # Check if the index is odd (not divisible by 2)
        if i%2!=0:
            t.append(a[i])   # If the index is odd, append the name to the 't' list
            
    # Find all 'div' tags with the class 'doctor-card__clinic' within the HTML
    for i in soup.find_all('div',class_='doctor-card__clinic'):
        d.append(i.text.strip())  # Append the cleaned text content of each 'div' tag (clinic address) to the 'd' list

    # Return the filtered doctor names ('t') and the clinic addresses ('d')
    
    return t,d  
    
    

# Fetch the HTML content of the specified URL
webpage=requests.get('https://us-uk.bookimed.com/doctors/country=germany/direction=check-up/').text
# Call the 'funvalue' function to extract data from the webpage
s=funvalue(webpage)
s

(['Marcel Dihne',
  'Sven Propson',
  'Sebastian Keil',
  'Markus Düx',
  'Ludger Wilhelm Poll',
  'Dr. Marion Eckert',
  'Prof. Uwe Mellies',
  'Prof. Heiko Stern',
  'Dr. Simon Mayer',
  'Prof. Stefan Eber',
  'Dr. Reinhard Erdl',
  'Dr. Linda Johnston-Rohrbasser',
  'Christian Molleken'],
 ['Medical Center in Solingen',
  'Medical Center in Solingen',
  'Medical Center in Solingen',
  'Nordwest Clinic (Krankenhaus)',
  'PRADUS Diagnostics',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'M1 Private Clinic',
  'PRADUS Diagnostics'])

In [265]:
df=pd.DataFrame(s[0])  # Create a Pandas DataFrame named 'df' from the first element of the 's' tuple (which contains doctor names)
df  # Print the 'df' DataFrame (doctor names)

                                0
0                    Marcel Dihne
1                    Sven Propson
2                  Sebastian Keil
3                      Markus Düx
4             Ludger Wilhelm Poll
5               Dr. Marion Eckert
6               Prof. Uwe Mellies
7               Prof. Heiko Stern
8                 Dr. Simon Mayer
9               Prof. Stefan Eber
10              Dr. Reinhard Erdl
11  Dr. Linda Johnston-Rohrbasser
12             Christian Molleken

In [267]:
df1=pd.DataFrame(s[1])  # Create a Pandas DataFrame named 'df1' from the second element of the 's' tuple (which contains clinic addresses)
df1

                                0
0      Medical Center in Solingen
1      Medical Center in Solingen
2      Medical Center in Solingen
3   Nordwest Clinic (Krankenhaus)
4              PRADUS Diagnostics
5               M1 Private Clinic
6               M1 Private Clinic
7               M1 Private Clinic
8               M1 Private Clinic
9               M1 Private Clinic
10              M1 Private Clinic
11              M1 Private Clinic
12             PRADUS Diagnostics

In [269]:
combined_df=pd.concat([df,df1],axis=1)   # Concatenate the 'df' and 'df1' DataFrames horizontally (axis=1) to combine names and addresses into a single DataFrame
combined_df  # Print the combined DataFrame

                                0                              0
0                    Marcel Dihne     Medical Center in Solingen
1                    Sven Propson     Medical Center in Solingen
2                  Sebastian Keil     Medical Center in Solingen
3                      Markus Düx  Nordwest Clinic (Krankenhaus)
4             Ludger Wilhelm Poll             PRADUS Diagnostics
5               Dr. Marion Eckert              M1 Private Clinic
6               Prof. Uwe Mellies              M1 Private Clinic
7               Prof. Heiko Stern              M1 Private Clinic
8                 Dr. Simon Mayer              M1 Private Clinic
9               Prof. Stefan Eber              M1 Private Clinic
10              Dr. Reinhard Erdl              M1 Private Clinic
11  Dr. Linda Johnston-Rohrbasser              M1 Private Clinic
12             Christian Molleken             PRADUS Diagnostics

In [271]:
combined_df.columns=['Name','Address']  # Set the column names of the combined DataFrame to 'Name' and 'Address'

In [273]:
combined_df    # Print the combined DataFrame with the updated column names

                             Name                        Address
0                    Marcel Dihne     Medical Center in Solingen
1                    Sven Propson     Medical Center in Solingen
2                  Sebastian Keil     Medical Center in Solingen
3                      Markus Düx  Nordwest Clinic (Krankenhaus)
4             Ludger Wilhelm Poll             PRADUS Diagnostics
5               Dr. Marion Eckert              M1 Private Clinic
6               Prof. Uwe Mellies              M1 Private Clinic
7               Prof. Heiko Stern              M1 Private Clinic
8                 Dr. Simon Mayer              M1 Private Clinic
9               Prof. Stefan Eber              M1 Private Clinic
10              Dr. Reinhard Erdl              M1 Private Clinic
11  Dr. Linda Johnston-Rohrbasser              M1 Private Clinic
12             Christian Molleken             PRADUS Diagnostics

In [287]:
df_combined=pd.concat([combined_column,combined_output],axis=0)    # Concatenate the 'combined_column' DataFrame (from the previous scraping) with the 'combined_output' DataFrame (from the current scraping) vertically (axis=0)

In [289]:
df_combined  # Print the combined DataFrame

                           Name                             Address
0                     Ralf Buhl          Medical Center in Solingen
1                 Andreas Gross          Asklepios Hospital Barmbek
2              Peter Paul Urban          Asklepios Hospital Barmbek
3                   Paul Kremer               Asklepios Nord Clinic
4               Ulrich Schaudig          Asklepios Hospital Barmbek
..                          ...                                 ...
261    Prof. Dr. Peter Mallmann  Clinic University Hospital Cologne
262     Prof. Dr. Rüdiger Lange   Clinic German Heart Center Munich
263         Dr. Robert Krempien  Clinic Helios Berlin-Buch Hospital
264   Prof. Dr. Rudiger Gerlach       Clinic Helios Hospital Erfurt
265  Prof. Dr. Joachim Fotiadis   Clinic German Heart Center Munich

[525 rows x 2 columns]

In [295]:
combined_output=pd.concat([df_combined,combined_df],axis=0)    # This line might be redundant, as 'combined_df' is already part of 'df_combined'. It seems like you're attempting to combine the DataFrames twice.

In [297]:
combined_output # Print the combined DataFrame

                             Name                     Address
0                       Ralf Buhl  Medical Center in Solingen
1                   Andreas Gross  Asklepios Hospital Barmbek
2                Peter Paul Urban  Asklepios Hospital Barmbek
3                     Paul Kremer       Asklepios Nord Clinic
4                 Ulrich Schaudig  Asklepios Hospital Barmbek
..                            ...                         ...
8                 Dr. Simon Mayer           M1 Private Clinic
9               Prof. Stefan Eber           M1 Private Clinic
10              Dr. Reinhard Erdl           M1 Private Clinic
11  Dr. Linda Johnston-Rohrbasser           M1 Private Clinic
12             Christian Molleken          PRADUS Diagnostics

[538 rows x 2 columns]

In [309]:
combined_output=combined_output.reset_index()   # Reset the index of the combined DataFrame to a standard numerical index starting from 0

In [317]:
combined_output  # Print the DataFrame with the reset index

     index                           Name                     Address
0        0                      Ralf Buhl  Medical Center in Solingen
1        1                  Andreas Gross  Asklepios Hospital Barmbek
2        2               Peter Paul Urban  Asklepios Hospital Barmbek
3        3                    Paul Kremer       Asklepios Nord Clinic
4        4                Ulrich Schaudig  Asklepios Hospital Barmbek
..     ...                            ...                         ...
533      8                Dr. Simon Mayer           M1 Private Clinic
534      9              Prof. Stefan Eber           M1 Private Clinic
535     10              Dr. Reinhard Erdl           M1 Private Clinic
536     11  Dr. Linda Johnston-Rohrbasser           M1 Private Clinic
537     12             Christian Molleken          PRADUS Diagnostics

[538 rows x 3 columns]

In [329]:
combined_output.drop(['index'],axis=1,inplace=True)  # Drop the redundant 'index' column that was created when resetting the index

In [331]:
combined_output # Print the final DataFrame with the index dropped

                              Name                     Address
0                        Ralf Buhl  Medical Center in Solingen
1                    Andreas Gross  Asklepios Hospital Barmbek
2                 Peter Paul Urban  Asklepios Hospital Barmbek
3                      Paul Kremer       Asklepios Nord Clinic
4                  Ulrich Schaudig  Asklepios Hospital Barmbek
..                             ...                         ...
533                Dr. Simon Mayer           M1 Private Clinic
534              Prof. Stefan Eber           M1 Private Clinic
535              Dr. Reinhard Erdl           M1 Private Clinic
536  Dr. Linda Johnston-Rohrbasser           M1 Private Clinic
537             Christian Molleken          PRADUS Diagnostics

[538 rows x 2 columns]

In [333]:
combined_output.to_excel(r"C:\Users\DELL\Desktop\Book1.xlsx")